name: Scalafmt
description: Format Scala source files with Scalafmt

branding:
  color: red
  icon: check-square

inputs:
  version:
    description: Version of scalafmt to use
    default: latest
    required: false
  format-files:
    description: If true then scalafmt will reformat source files instead of checking
    default: 'false'
    required: false
  compare-branch:
    description: Branch to compare against to filter only changed files
    required: false
  use-gitignore:
    description: If true then the .gitignore file will be used to filter sources
    default: 'true'
    required: false
  path:
    description: Path(s) to scan
    default: .
    required: false

runs:
  using: node12
  main: dist/index.js
