name: tests
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  integration_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          version: 2.7.5
          path: integration-test
          compare-branch: diff-branch